### ISSUE TITLE
2.4.0 milestone closed but not yet released

### ISSUE THREAD

**Issue by PowerKiKi** [mezzio/mezzio-laminasviewrenderer#13]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.4.0

#### Summary

I see the [milestone 2.4.0](https://github.com/mezzio/mezzio-laminasviewrenderer/milestone/5) was closed in october. I assume this means that an automatic release should have happened back then. However I don't see any 2.4.0 release. The [most recent release is 2.3.0](https://github.com/mezzio/mezzio-laminasviewrenderer/releases).

Is it a mishap of automatic release ? or is it intentional ?

#### Current behavior

2.4.0 is not released

#### Expected behavior

Have 2.4.0 released

**Comment by froschdesign** [comment]
@PowerKiKi 
Uff, the workflow is missing: https://github.com/mezzio/mezzio-laminasviewrenderer/tree/2.4.x/.github/workflows
Compare with: https://github.com/laminas/laminas-cache/tree/3.2.x/.github/workflows

**Comment by Ocramius** [comment]
I re-opened the milestone: we're missing the `laminas/automatic-releases` workflow here 😬
